"""Stack domain models and validation."""

from hotcards.domain.image_dependencies import (
    ImageSourceDependency,
    image_source_dependencies,
)
from hotcards.domain.image_dimensions import (
    AspectRatio,
    GenerateResolution,
    output_dimensions,
)
from hotcards.domain.models import (
    CURRENT_SCHEMA_VERSION,
    AcceptedEdit,
    Background,
    CanvasSize,
    Card,
    CardReference,
    CardRevision,
    DirectGenerateProvenance,
    EditPreserveOptions,
    EditProvenance,
    GeneratedBackground,
    GenerateInputs,
    HotspotConditions,
    HotspotKeyChanges,
    HotspotSet,
    ImageOperationSettings,
    ImageProvenance,
    ImageReferenceSnapshot,
    ImageSourceSnapshot,
    Interaction,
    KeyDefinition,
    LegacyGenerateProvenance,
    NavigateAction,
    Point,
    Polygon,
    RefineProvenance,
    RefineTransformation,
    ResolvedCardReference,
    RunOverlayMode,
    Stack,
    UnresolvedCardReference,
)
from hotcards.domain.validation import normalize_card_name, require_unique_card_names

__all__ = [
    "AcceptedEdit",
    "AspectRatio",
    "CURRENT_SCHEMA_VERSION",
    "Background",
    "CanvasSize",
    "Card",
    "CardRevision",
    "CardReference",
    "DirectGenerateProvenance",
    "EditPreserveOptions",
    "EditProvenance",
    "GenerateInputs",
    "GenerateResolution",
    "GeneratedBackground",
    "HotspotConditions",
    "HotspotKeyChanges",
    "HotspotSet",
    "ImageOperationSettings",
    "ImageProvenance",
    "ImageReferenceSnapshot",
    "ImageSourceDependency",
    "ImageSourceSnapshot",
    "Interaction",
    "KeyDefinition",
    "LegacyGenerateProvenance",
    "NavigateAction",
    "Point",
    "Polygon",
    "RefineProvenance",
    "RefineTransformation",
    "ResolvedCardReference",
    "RunOverlayMode",
    "Stack",
    "UnresolvedCardReference",
    "image_source_dependencies",
    "normalize_card_name",
    "output_dimensions",
    "require_unique_card_names",
]
