"""Stack domain models and validation."""

from hotcards.domain.models import (
    CURRENT_SCHEMA_VERSION,
    Background,
    CanvasSize,
    Card,
    CardReference,
    CardRevision,
    GeneratedBackground,
    HotspotConditions,
    HotspotKeyChanges,
    HotspotSet,
    ImageGenerationInputs,
    ImageGenerationMetadata,
    ImagePrompt,
    ImageReferenceSnapshot,
    Interaction,
    KeyDefinition,
    LegacyImageGenerationInputs,
    NavigateAction,
    Point,
    Polygon,
    ReferenceRole,
    ResolvedCardReference,
    RunOverlayMode,
    Stack,
    UnresolvedCardReference,
)
from hotcards.domain.validation import normalize_card_name, require_unique_card_names

__all__ = [
    "CURRENT_SCHEMA_VERSION",
    "Background",
    "CanvasSize",
    "Card",
    "CardRevision",
    "CardReference",
    "GeneratedBackground",
    "HotspotConditions",
    "HotspotKeyChanges",
    "HotspotSet",
    "ImageGenerationInputs",
    "ImageGenerationMetadata",
    "ImagePrompt",
    "ImageReferenceSnapshot",
    "Interaction",
    "KeyDefinition",
    "LegacyImageGenerationInputs",
    "NavigateAction",
    "Point",
    "Polygon",
    "ReferenceRole",
    "ResolvedCardReference",
    "RunOverlayMode",
    "Stack",
    "UnresolvedCardReference",
    "normalize_card_name",
    "require_unique_card_names",
]
