"""Stack domain models and validation."""

from hypergen.domain.models import (
    CURRENT_SCHEMA_VERSION,
    Background,
    CanvasSize,
    Card,
    CardReference,
    CardRevision,
    GeneratedBackground,
    GenerationStyle,
    HotspotGenerationProvenance,
    HotspotSet,
    ImageGenerationInputs,
    ImageGenerationMetadata,
    ImageOrigin,
    ImageRevision,
    ImportedBackground,
    Interaction,
    NavigateAction,
    Point,
    Polygon,
    ResolvedCardReference,
    RunOverlayMode,
    Stack,
    UnresolvedCardReference,
)
from hypergen.domain.validation import normalize_card_name, require_unique_card_names

__all__ = [
    "CURRENT_SCHEMA_VERSION",
    "Background",
    "CanvasSize",
    "Card",
    "CardRevision",
    "CardReference",
    "GeneratedBackground",
    "GenerationStyle",
    "HotspotGenerationProvenance",
    "HotspotSet",
    "ImageGenerationInputs",
    "ImageGenerationMetadata",
    "ImageOrigin",
    "ImageRevision",
    "ImportedBackground",
    "Interaction",
    "NavigateAction",
    "Point",
    "Polygon",
    "ResolvedCardReference",
    "RunOverlayMode",
    "Stack",
    "UnresolvedCardReference",
    "normalize_card_name",
    "require_unique_card_names",
]
